/* eslint-disable */
// Authored devotional content keyed by day_number.
// { s: summary, q: think-about question, p: prayer, quote: REAL verse from the day's readings }
// Quotes are actual scripture from that day's readings. Days not listed here
// receive a period-aware fallback (no quote) generated in generatePlan.js.

module.exports = {
  1: {
    s: 'God creates the heavens and the earth, ordering light and dark, sea and land, and filling the world with living things. On the sixth day he makes man and woman in his own image and calls creation very good. The seventh day he rests, blessing it and making it holy.',
    q: 'Where do you most need to remember today that you are made in the image of God and called "very good"?',
    p: 'Father, Creator of all that is, thank you for the gift of life and for making me in your image. Help me to see your goodness in the world you have made and to rest in you. Amen.',
    quote: '“So God created man in his own image, in the image of God he created him; male and female he created them.” (Genesis 1:27)',
  },
  2: {
    s: 'Adam and Eve listen to the serpent and eat the forbidden fruit, and sin enters the world along with shame, blame, and death. God pronounces the consequences yet already promises that the woman’s offspring will crush the serpent. Their son Cain then murders his brother Abel out of jealousy.',
    q: 'When you fail, do you tend to hide from God like Adam, or come to him honestly for mercy?',
    p: 'Lord, when I am tempted to hide my sin or blame others, draw me back to you. Thank you that even in the garden you promised a Savior. Amen.',
    quote: '“The LORD God called to the man, and said to him, “Where are you?”” (Genesis 3:9)',
  },
  4: {
    s: 'The wickedness of humanity grows, but Noah finds favor with God. God sends a flood to cleanse the earth and saves Noah, his family, and the animals in the ark. Afterward God sets the rainbow in the sky as the sign of his covenant never again to destroy the earth by flood.',
    q: 'What "rainbow" reminders of God’s faithfulness can you point to in your own life?',
    p: 'Faithful God, thank you for your mercy that carried Noah through the storm. Help me to trust your promises when the waters rise around me. Amen.',
    quote: '“I set my bow in the cloud, and it shall be a sign of the covenant between me and the earth.” (Genesis 9:13)',
  },
  6: {
    s: 'God calls Abram to leave his homeland with the promise to make him a great nation and to bless all peoples through him. Meanwhile we meet Job, a blameless and upright man whom God permits to be tested through devastating loss. Job’s faith holds even as everything is stripped away.',
    q: 'Is God asking you to step out in trust toward something unseen, as he asked of Abram?',
    p: 'Father, like Abram, give me the faith to go where you call, and like Job, the grace to bless your name in loss as well as gain. Amen.',
    quote: '“The LORD gave, and the LORD has taken away; blessed be the name of the LORD.” (Job 1:21)',
  },
  11: {
    s: 'God tests Abraham, asking him to offer his son Isaac on Mount Moriah. Abraham obeys in faith, and at the last moment God provides a ram in Isaac’s place and renews his covenant promise. The chapter foreshadows the Father who would one day give his own Son.',
    q: 'What is the "Isaac" you find hardest to surrender to God in trust?',
    p: 'Father, you provided for Abraham on the mountain and you provide for me still. Give me the faith to trust you even with what I hold most dear. Amen.',
    quote: '“God will provide himself the lamb for a burnt offering, my son.” (Genesis 22:8)',
  },
  19: {
    s: 'Joseph, favored by his father Jacob, dreams of his family bowing before him, stirring his brothers’ jealousy. They seize him and sell him into slavery in Egypt, deceiving their father into thinking he is dead. God’s providence is quietly at work even in this betrayal.',
    q: 'Where might God be working for good through a situation that feels like betrayal or loss?',
    p: 'Lord, when others wound me, help me trust that you are still writing the story. Keep my heart free of bitterness as I wait on you. Amen.',
    quote: '“Here comes this dreamer.” (Genesis 37:19)',
  },
  24: {
    s: 'Joseph reveals himself to his brothers in Egypt, weeping and forgiving them rather than taking revenge. He sees that God used their evil intent to preserve many lives during the famine. Jacob’s whole family is reunited and settles in Egypt.',
    q: 'Is there someone you need to forgive, trusting that God can bring good even from the harm done?',
    p: 'Merciful God, give me Joseph’s heart to forgive and to see your hand even in hard seasons. Heal the wounds I still carry. Amen.',
    quote: '“You meant evil against me; but God meant it for good.” (Genesis 50:20)',
  },
  27: {
    s: 'A new pharaoh enslaves the Israelites, but God raises up Moses, drawn from the Nile and preserved for a purpose. The book of Leviticus opens with instructions for the burnt offering, teaching Israel to approach a holy God. The story turns from family to nation.',
    q: 'How do you make space in your life to approach God with reverence rather than rushing past him?',
    p: 'Lord, you preserved Moses for your purposes and you have a purpose for me. Teach me to come before you with reverence and trust. Amen.',
    quote: '“I have been a sojourner in a foreign land.” (Exodus 2:22)',
  },
  28: {
    s: 'At the burning bush God calls Moses to confront Pharaoh and lead Israel out of slavery. When Moses asks God’s name, God reveals himself as "I AM WHO I AM." Holy ground, holy fire, and a holy name mark this turning point in salvation history.',
    q: 'Where is your "burning bush", a place God may be calling you that you feel unworthy to answer?',
    p: 'I AM, holy and faithful God, you meet me on ordinary ground and call me by name. Give me courage to answer when you call. Amen.',
    quote: '“I AM WHO I AM.” (Exodus 3:14)',
  },
  34: {
    s: 'God institutes the Passover: each household marks its doorposts with the blood of a lamb so the destroyer passes over them. That night the firstborn of Egypt die, and Pharaoh finally lets Israel go. The meal becomes a perpetual memorial of God’s deliverance.',
    q: 'How does remembering God’s past deliverance strengthen you to trust him now?',
    p: 'Lord, the blood of the lamb spared your people, and the blood of Christ saves me. Thank you for passing over my sin and setting me free. Amen.',
    quote: '“When I see the blood, I will pass over you.” (Exodus 12:13)',
  },
  35: {
    s: 'Israel reaches the Red Sea with Pharaoh’s army closing in. God parts the waters so they cross on dry ground, then closes the sea over the Egyptians. The people are saved by the mighty hand of God, not by their own strength.',
    q: 'What "Red Sea" are you facing where you need to stand still and trust God to act?',
    p: 'Lord, when I am trapped between fear and an impossible sea, remind me that the battle is yours. Help me to be still and watch you work. Amen.',
    quote: '“The LORD will fight for you, and you have only to be still.” (Exodus 14:14)',
  },
  38: {
    s: 'At Mount Sinai God descends in fire and cloud and gives the Ten Commandments. He calls Israel to be his treasured possession, a holy nation set apart to him. The Law is given not to burden but to form a people in covenant love.',
    q: 'Which of God’s commands is he inviting you to take more seriously as a path to freedom, not restriction?',
    p: 'Lord, you gave your Law in love to shape a holy people. Write your commandments on my heart and help me walk in them gladly. Amen.',
    quote: '“You shall have no other gods before me.” (Exodus 20:3)',
  },
  57: {
    s: 'Numbers gives instructions for the Nazirite vow, set apart to the Lord, and the beautiful priestly blessing. In Deuteronomy Moses gives the Shema, the great command to love the Lord with all one’s heart, soul, and might. Israel is called to keep these words ever before them.',
    q: 'What would it look like today to love God with all your heart, soul, and strength in one concrete way?',
    p: 'Lord our God, you are one, and you are worthy of all my love. Bless me and keep me, and let your face shine upon me this day. Amen.',
    quote: '“Hear, O Israel: The LORD our God is one LORD; and you shall love the LORD your God with all your heart.” (Deuteronomy 6:4-5)',
  },
  63: {
    s: 'Twelve spies scout the Promised Land, but ten bring back a fearful report and the people rebel, refusing to enter. Because of their unbelief, that generation is condemned to wander forty years in the wilderness. Only Caleb and Joshua trusted God’s promise.',
    q: 'Where is fear keeping you from stepping into something God has already promised to give?',
    p: 'Lord, forgive me when I shrink back in fear instead of trusting your promise. Give me the faith of Caleb to follow you fully. Amen.',
    quote: '“Let us go up at once, and occupy it; for we are well able to overcome it.” (Numbers 13:30)',
  },
  81: {
    s: 'After Moses’ death, God commissions Joshua to lead Israel across the Jordan into the Promised Land. He commands Joshua to be strong and courageous and to meditate on the Law day and night. The waters of the Jordan part as the people cross over.',
    q: 'What fear is God meeting today with his promise to be with you wherever you go?',
    p: 'Lord, you go before me and beside me. Make me strong and courageous, not in myself but in your faithful presence. Amen.',
    quote: '“Be strong and of good courage… for the LORD your God is with you wherever you go.” (Joshua 1:9)',
  },
  88: {
    s: 'Joshua gathers the tribes at Shechem and recounts all God has done, then calls them to choose whom they will serve. He pledges that he and his household will serve the Lord. The people renew their covenant before God.',
    q: 'In practical terms, what would it mean for your household to "serve the Lord" this week?',
    p: 'Lord, today I choose you. Help me and those I love to serve you faithfully, turning from every idol that competes for our hearts. Amen.',
    quote: '“As for me and my house, we will serve the LORD.” (Joshua 24:15)',
  },
  96: {
    s: 'Hannah, barren and grieving, pours out her heart to God and vows to give her son to the Lord. God answers, and she bears Samuel, whom she brings to serve at the temple. Her song of praise exalts the God who lifts up the lowly.',
    q: 'What deep longing do you need to pour out honestly before God today?',
    p: 'Lord, like Hannah I bring you my longings and my tears. Thank you that you hear me, and help me to entrust my whole life back to you. Amen.',
    quote: '“For this child I prayed; and the LORD has granted me my petition.” (1 Samuel 1:27)',
  },
  99: {
    s: 'John’s Gospel opens by declaring that the eternal Word became flesh and dwelt among us. John the Baptist points to Jesus as the Lamb of God, and Jesus is born anew in the conversation with Nicodemus. We pause from the Old Testament to behold Christ himself.',
    q: 'What would change if you truly believed God so loved the world that he gave his only Son for you?',
    p: 'Lord Jesus, eternal Word made flesh, thank you for dwelling among us. Open my eyes to behold your glory full of grace and truth. Amen.',
    quote: '“And the Word became flesh and dwelt among us, full of grace and truth.” (John 1:14)',
  },
  105: {
    s: 'Jesus is crucified, dies, and is buried, then rises from the dead on the third day. He appears to Mary Magdalene and the disciples, and restores Peter with the threefold call to feed his sheep. The Gospel of John closes with the promise of life in his name.',
    q: 'Like Peter, where do you need to hear Jesus ask, "Do you love me?" and respond again?',
    p: 'Risen Lord, you conquered death and call me by name. Restore me where I have failed and send me to love as you have loved me. Amen.',
    quote: '“Peace be with you.” (John 20:19)',
  },
  110: {
    s: 'The Philistine giant Goliath defies Israel’s armies, and no one dares face him, until the shepherd boy David comes in the name of the Lord. With a sling and a stone he defeats the giant, showing that the battle belongs to God. Israel is delivered through unlikely faith.',
    q: 'What "giant" are you facing that you need to confront in the name of the Lord rather than in your own strength?',
    p: 'Lord, the battle belongs to you. Give me David’s courage to face what frightens me, trusting not in my strength but in your name. Amen.',
    quote: '“The battle is the LORD’s, and he will give you into our hand.” (1 Samuel 17:47)',
  },
  130: {
    s: 'Confronted by the prophet Nathan over his sin with Bathsheba and Uriah, David repents. Psalm 51, his great prayer of repentance, cries out for a clean heart and a renewed spirit. God’s mercy meets David’s honest confession.',
    q: 'Is there a sin you have been minimizing that God is inviting you to confess honestly today?',
    p: 'Create in me a clean heart, O God, and put a new and right spirit within me. Do not cast me from your presence, but restore the joy of your salvation. Amen.',
    quote: '“Create in me a clean heart, O God, and put a new and right spirit within me.” (Psalm 51:10)',
  },
  143: {
    s: 'As David’s reign ends, Solomon is established as king. At Gibeon God offers Solomon whatever he asks, and Solomon requests an understanding heart to govern God’s people wisely. Pleased, God grants him wisdom along with riches and honor.',
    q: 'If God offered you one request today, what does your honest answer reveal about your heart?',
    p: 'Lord, like Solomon I ask not first for riches but for wisdom, an understanding heart to discern good from evil and to serve you well. Amen.',
    quote: '“Give your servant therefore an understanding mind to govern your people.” (1 Kings 3:9)',
  },
  144: {
    s: 'David charges Solomon to walk in God’s ways before his death, and Solomon secures his throne. In Chronicles, Solomon begins preparations to build the temple of the Lord in Jerusalem, gathering workers and materials. The great house of worship is set in motion.',
    q: 'What "house", a habit, relationship, or work, is God asking you to build carefully for his glory?',
    p: 'Lord, as Solomon prepared to build your temple, help me to build my life as a dwelling place for you. Keep me walking in your ways. Amen.',
    quote: '“Be strong, and show yourself a man.” (1 Kings 2:2)',
  },
  154: {
    s: 'Mark’s fast-paced Gospel opens with John the Baptist preparing the way and Jesus’ baptism, where the Father’s voice declares him the beloved Son. Jesus begins proclaiming the kingdom, calling disciples, and healing the sick. We pause again to fix our eyes on Christ.',
    q: 'What is one thing Jesus is calling you to leave behind in order to follow him more closely?',
    p: 'Lord Jesus, beloved Son of the Father, you call me to follow you. Give me the readiness of the first disciples to leave my nets and come. Amen.',
    quote: '“The time is fulfilled, and the kingdom of God is at hand; repent, and believe in the gospel.” (Mark 1:15)',
  },
  161: {
    s: 'Jesus is condemned, mocked, and crucified, crying out and breathing his last as the temple curtain tears in two. A centurion confesses him as the Son of God. On the third day the women find the tomb empty and hear that he has risen.',
    q: 'Standing at the cross and the empty tomb, what do you most need to bring to the risen Christ today?',
    p: 'Crucified and risen Lord, the curtain is torn and the way to the Father is open. Thank you for dying for me and rising to give me life. Amen.',
    quote: '“Truly this man was the Son of God!” (Mark 15:39)',
  },
  166: {
    s: 'Elijah confronts the prophets of Baal on Mount Carmel, and God answers with fire from heaven, proving he alone is God. The drought breaks as rain returns at Elijah’s word. The chapters call a divided people back to wholehearted worship.',
    q: 'Where are you "limping between two opinions," and how is God calling you to choose him fully?',
    p: 'Lord, you alone are God. Send your fire to consume my divided loyalties and draw my whole heart back to wholehearted worship of you. Amen.',
    quote: '“How long will you go limping between two different opinions?” (1 Kings 18:21)',
  },
  216: {
    s: 'Isaiah delivers the great Suffering Servant prophecy, foretelling one who would be wounded for our transgressions and bear the sins of many. Ezekiel’s visions continue alongside. Centuries before Christ, the cost and meaning of his sacrifice are foreshadowed.',
    q: 'How does it change your day to know that Christ was "wounded for your transgressions"?',
    p: 'Lord Jesus, my Suffering Servant, you were pierced for my sins and by your wounds I am healed. Thank you for bearing what I could never carry. Amen.',
    quote: '“He was wounded for our transgressions… and with his stripes we are healed.” (Isaiah 53:5)',
  },
  245: {
    s: 'In the midst of exile and judgment, Jeremiah proclaims the promise of a new covenant that God will write upon the heart. God pledges to forgive iniquity and remember sin no more. Hope breaks through the darkness of Israel’s loss.',
    q: 'What does it mean to you that God wants to write his law on your heart, not just on stone?',
    p: 'Lord, write your law upon my heart and be my God. Thank you for the new covenant in Christ that forgives my sin and makes me yours. Amen.',
    quote: '“I will put my law within them, and I will write it upon their hearts.” (Jeremiah 31:33)',
  },
  258: {
    s: 'Matthew opens with the genealogy and birth of Jesus, the long-awaited Messiah, called Emmanuel, "God with us." After his baptism and temptation in the wilderness, Jesus begins to preach the kingdom and calls his first disciples. The promised King has come.',
    q: 'Where do you most need to know "God with us", Emmanuel, in your life right now?',
    p: 'Emmanuel, God with us, thank you for coming to dwell among your people. Be with me in every part of my life and lead me into your kingdom. Amen.',
    quote: '“His name shall be called Emmanuel (which means, God with us).” (Matthew 1:23)',
  },
  259: {
    s: 'Jesus preaches the Sermon on the Mount, beginning with the Beatitudes that turn the world’s values upside down. He teaches on prayer, anxiety, and trusting the Father, and gives the Lord’s Prayer. This is the charter of life in the kingdom of God.',
    q: 'Which Beatitude unsettles or comforts you most today, and why?',
    p: 'Father, teach me the way of the kingdom, to hunger for righteousness, to make peace, and to seek first your kingdom above all else. Amen.',
    quote: '“But seek first the kingdom of God and his righteousness, and all these things shall be yours as well.” (Matthew 6:33)',
  },
  266: {
    s: 'Jesus is crucified and dies, and the earth shakes as the temple curtain is torn. On the third day he rises, and the women meet him with joy. He commissions the disciples to make disciples of all nations, promising to be with them always.',
    q: 'How are you living out the Great Commission to make disciples in your own circle?',
    p: 'Risen Lord, you hold all authority and you send me out. Give me courage to share your good news, trusting you are with me to the end of the age. Amen.',
    quote: '“Go therefore and make disciples of all nations… and lo, I am with you always.” (Matthew 28:19-20)',
  },
  276: {
    s: 'As the returned exiles face danger, Esther is urged to risk her life by appealing to the king for her people. Mordecai reminds her she may have come to royal position "for such a time as this." She resolves to act, trusting God.',
    q: 'For what purpose might God have placed you exactly where you are "for such a time as this"?',
    p: 'Lord, you place your people where they are needed. Give me Esther’s courage to act for others, even at cost, trusting you with the outcome. Amen.',
    quote: '“And who knows whether you have not come to the kingdom for such a time as this?” (Esther 4:14)',
  },
  304: {
    s: 'Second Maccabees recounts the heroic mother and her seven sons who choose death rather than betray God’s law, confident in the resurrection. The Wisdom of Solomon affirms that the souls of the righteous are in the hand of God. Faith shines under brutal persecution.',
    q: 'What conviction would you hold to even at great cost, trusting in God’s promise of life?',
    p: 'Lord, give me the courage of the faithful who trusted you beyond death. Hold my life in your hand and strengthen me to stand firm. Amen.',
    quote: '“The souls of the righteous are in the hand of God.” (Wisdom 3:1)',
  },
  313: {
    s: 'Luke’s Gospel begins with the announcements to Zechariah and Mary, Mary’s Magnificat, and the birth of Jesus in Bethlehem. Angels proclaim good news of great joy to the shepherds. The Savior is born, and heaven rejoices.',
    q: 'Like Mary, where is God inviting you to say "let it be to me according to your word"?',
    p: 'Lord, like Mary may my soul magnify you. Thank you for the Savior born in Bethlehem; let your great joy fill my heart this day. Amen.',
    quote: '“For to you is born this day in the city of David a Savior, who is Christ the Lord.” (Luke 2:11)',
  },
  321: {
    s: 'Jesus prays in agony in the garden, is betrayed, crucified, and dies, then rises on the third day. He walks unrecognized with two disciples on the road to Emmaus, opening the Scriptures and being known in the breaking of the bread. He ascends, blessing his disciples.',
    q: 'Where might Jesus be walking with you unrecognized, waiting to be known in word and sacrament?',
    p: 'Risen Lord, open the Scriptures to me and be known to me in the breaking of the bread. Make my heart burn within me as you draw near. Amen.',
    quote: '“Did not our hearts burn within us… while he opened to us the scriptures?” (Luke 24:32)',
  },
  323: {
    s: 'At Pentecost the Holy Spirit descends on the disciples with wind and fire, and Peter boldly proclaims the risen Christ. Three thousand are baptized and the Church is born. In Romans, Paul lays out humanity’s need for the righteousness that comes through faith.',
    q: 'How are you making room for the Holy Spirit to empower your witness, as the first disciples did?',
    p: 'Holy Spirit, fall afresh on me as you did at Pentecost. Make me a bold witness to the risen Christ and draw many to his name. Amen.',
    quote: '“And they were all filled with the Holy Spirit.” (Acts 2:4)',
  },
  326: {
    s: 'Peter and the apostles are arrested but rejoice to suffer for the name of Jesus. In Romans 8, Paul declares that there is no condemnation for those in Christ and that nothing can separate us from the love of God. It is one of Scripture’s great mountaintops of hope.',
    q: 'What fear or accusation do you need to surrender to the truth that nothing can separate you from God’s love?',
    p: 'Father, thank you that in Christ there is no condemnation and nothing can separate me from your love. Let that truth anchor me today. Amen.',
    quote: '“For I am sure that neither death nor life… will be able to separate us from the love of God in Christ Jesus.” (Romans 8:38-39)',
  },
  330: {
    s: 'Saul, the persecutor, is struck down on the road to Damascus by the risen Jesus and is converted to become the great apostle Paul. In Romans, Paul urges believers to offer themselves as a living sacrifice and to overcome evil with good. Grace transforms an enemy into a servant.',
    q: 'Where do you need to trust that God can radically transform a heart, yours or someone else’s?',
    p: 'Lord, you turned a persecutor into an apostle. Transform me by your grace and help me overcome evil with good, offering myself to you. Amen.',
    quote: '“Saul, Saul, why do you persecute me?” (Acts 9:4)',
  },
  337: {
    s: 'As the Gospel spreads, Paul gives the Church the great hymn of love in 1 Corinthians 13: love is patient and kind, and the greatest of these is love. Without love, every gift is empty. It is the heart of the Christian life.',
    q: 'Reading "love is patient, love is kind," where is love being asked of you that feels costly today?',
    p: 'Lord, you are love itself. Make my love patient and kind, free of envy and pride, so that whatever I do is done in love. Amen.',
    quote: '“So faith, hope, love abide, these three; but the greatest of these is love.” (1 Corinthians 13:13)',
  },
  349: {
    s: 'Paul finally reaches Rome, where he preaches the kingdom boldly though under guard. To the Philippians he writes of rejoicing in the Lord always and of pressing on toward the goal in Christ. Even in chains, his joy and mission are unbroken.',
    q: 'What would it look like to "rejoice in the Lord always" in the middle of your current circumstances?',
    p: 'Lord, teach me to rejoice in you always, in plenty and in want. Help me press on toward the goal of knowing Christ above all. Amen.',
    quote: '“Rejoice in the Lord always; again I will say, Rejoice.” (Philippians 4:4)',
  },
  362: {
    s: 'Revelation unveils the cosmic battle and the woman clothed with the sun, while Hebrews proclaims Jesus as the radiance of God’s glory and the great high priest. Christ is shown as supreme over angels and the perfect mediator of a better covenant. Heaven and earth meet in him.',
    q: 'How does seeing Jesus as your great high priest change the way you bring your needs to God?',
    p: 'Lord Jesus, radiance of the Father’s glory and my great high priest, thank you for interceding for me. Help me draw near with confidence. Amen.',
    quote: '“He reflects the glory of God and bears the very stamp of his nature.” (Hebrews 1:3)',
  },
  365: {
    s: 'The Bible closes with a new heaven and a new earth, where God dwells with his people and wipes away every tear. Hebrews recounts the great cloud of witnesses who lived by faith. The Spirit and the Bride say "Come," and Jesus promises, "I am coming soon."',
    q: 'As you finish the whole story of Scripture, what is one way God has changed your heart this year?',
    p: 'Lord, you make all things new and will one day wipe away every tear. Thank you for walking with me through your word. Come, Lord Jesus. Amen.',
    quote: '“Behold, I make all things new.” (Revelation 21:5)',
  },
};
