const fs = require('fs');
const src = fs.readFileSync(__dirname + '/../src/data/readingPlan.ts', 'utf8');
const marker = 'ReadingDay[] = ';
const start = src.indexOf('[', src.indexOf(marker) + marker.length);
const json = src.substring(start, src.lastIndexOf(']') + 1);
const plan = JSON.parse(json);
console.log('Total records:', plan.length);
const find = (n) => plan.find((d) => d.day_number === n);
const show = (d) => `Day ${d.day_number}: ${d.reading_one} / ${d.reading_two || '(none)'} / ${d.psalm_proverb}`;
console.log(show(find(1)));
console.log(show(find(144)));
console.log(show(find(365)));
const missing = plan.filter((d) => !d.reading_one || !d.reading_one.trim());
console.log('Missing reading_one:', missing.length ? missing.map((d) => d.day_number).join(',') : 'none');
const withQuote = plan.filter((d) => d.quote).length;
console.log('With quote:', withQuote, '| fallback (no quote):', plan.length - withQuote);
const days = plan.map((d) => d.day_number);
const dupes = days.filter((d, i) => days.indexOf(d) !== i);
console.log('Duplicate/contiguity issue:', dupes.length ? dupes.join(',') : 'none, 1..365 complete');
